on:
  push:
    branches:
      - main

name: FTP-Deploy-Action

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Print Working Directory
      run: pwd

    - name: Clean Workspace
      run: rm -rf *

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install NPM packages
      run: npm install

    - name: Build project
      run: npm run build

    - name: Sync files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }} 

    - name: Debug Deployment
      run: |
        ls -la ./fashion/  # List files in the deployment directory
        cat /path/to/ftp-deploy-action.log  # Print contents of the action's log file (if available)
